server:
  port: 8088

dataSource:
  url: jdbc:mysql://rm-uf6bbox2e82z6d12ho.mysql.rds.aliyuncs.com:3306/rdms?useUnicode=true&characterEncoding=utf8
  username: root
  password: MENGfw0430
  driverClassName: com.mysql.jdbc.Driver
app:
  staticPathPattern: /static/**
  staticPath: classpath:/static/
  loginUrl : /static/page/login.html

spring:
  redis:
#    host: r-2ze6331b49eed314.redis.rds.aliyuncs.com
#    port: 6379
#    username: mengfw
#    password: MENGfw0430

    host: 127.0.0.1
    port: 6379
